### PR TITLE
[1.1.0]

### PR DESCRIPTION
**Pull request by the-last-code-bender**
I've added a changelog file. You can read the changes from there. I created a version name. Considering your version as 1.0.0, I continued naming with version 1.1.0.

### CODE REVIEW

**Comment by cbrake** [comment]
Lots of good ideas here, thanks for the PR.

Questions:

- what is `#gplm_DSN.kicad_dbl`? The name does not clearly show me what is different from the original.
- we have several users fairly committed to `con` for connectors -- what if we renamed all the csv files to g-xxx.csv to work around the `con` filename issue? We already use this convention on the symbol and footprint libs so they group nicely in KiCad symbol/footprint browsers.
- what does the `g_`  add to the database, footprint, symbol names? 
- could we remove the `doc/` directory and leave assets at the root. Since all the documentation is at the root, it seems this make sense.
- I prefer to leave `envsetup.sh` named as is, as that is a common name and pattern in various Linux build systems.

We also have a bunch of changes on another project -- I'll get them pushed and merged now -- hopefully that will not create merge conflicts with what you've already done.

**Comment by the-last-code-bender** [comment]
> Lots of good ideas here, thanks for the PR.
> 
> Questions:
> 
> * what is `#gplm_DSN.kicad_dbl`? The name does not clearly show me what is different from the original.
> * we have several users fairly committed to `con` for connectors -- what if we renamed all the csv files to g-xxx.csv to work around the `con` filename issue? We already use this convention on the symbol and footprint libs so they group nicely in KiCad symbol/footprint browsers.
> * what does the `g_`  add to the database, footprint, symbol directory names?
> * could we remove the `doc/` directory and leave `assets` at the root. Since all the documentation is at the root, it seems this make sense.
> * I prefer to leave `envsetup.sh` named as is, as that is a common name and pattern in various Linux build systems.
> 
> We also have a bunch of changes on another project -- I'll get them pushed and merged now -- hopefully that will not create merge conflicts with what you've already done.

- The `cwd` command does not work on Windows. I tried running it with the `CD` command but was unsuccessful. I tried the SQLite connection string from [this link](https://www.connectionstrings.com/sqlite3-odbc-driver/), but I couldn’t establish the database connection. I downloaded the driver from [this site](http://www.ch-werner.de/sqliteodbc/), created a database through the application interface, and managed to connect by providing a DSN (data source name). A connection string field for DSN connection can be added to the README without replacing the old file.
- Since the issue is only with the file name being 'con', updating the names of the CSV files might be a better option.
- Since most of the naming in the project starts with 'g-', I had considered adding the 'g_' prefix to the folder names as well, thinking it was a project-specific convention. It holds no special meaning for me.
- I had considered defining the usage steps in the README file in separate .md files and placing all the documentation inside a doc folder. I thought this would make it easier for anyone looking at the project to understand the source files and documentation more clearly.
- The naming of envsetup.sh gave the impression that it automatically handles all the configurations for the entire project with a single file. However, the file actually only creates and updates a database from CSV files. But if you prefer it that way, it’s not a big deal. It can remain as envsetup.

**Comment by the-last-code-bender** [comment]
> A few more comments after discussing with the existing GitPLM users:
> 
> * we feel the `symbol`, `footprint` and `database` directories add value and help a lot to organize things, but we would prefer not to add the `src` level as that does not seem justified for only 3 subdirs.
> * Please leave `sqlite.exe` out of the repo. README.md could have instructions on how to install that.

- What do you think about the 3D models or the simulation files?
- Yes, it seems more logical.

**Comment by cbrake** [comment]
> * What do you think about the 3D models or the simulation files?

We currently have a separate repo for those: https://github.com/git-plm/3d-models

We do this because the size of these files can be quite large, and not everyone may want to check out this repo.

We are discussing organizing this better.

**Comment by cbrake** [comment]
> * The naming of envsetup.sh gave the impression that it automatically handles all the configurations for the entire project with a single file. However, the file actually only creates and updates a database from CSV files. But if you prefer it that way, it’s not a big deal. It can remain as envsetup.

The way `envsetup.sh` works on Linux is you source the file and it populates your shell with a bunch of functions you can then run.  So after I source it, I can interactively run:

- parts_db_create
- parts_db_watch
- parts_db_edit

So it is a little different than a script than you run.

**Comment by cbrake** [comment]
Good discussion, I'll merge our latest changes, make some directory changes, add your bat file, and then perhaps you can merge and add whatever documentation you feel is helpful for windows users if you are inclined to.

**Comment by cbrake** [comment]
closing this as I think it makes more sense to create a new PR.

**Pull request closed without merging**
